# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=200)),
                ('ocupacion', models.CharField(choices=[('Sector Empresarial', 'Sector Empresarial'), ('Empresa propia', 'Empresa propia'), ('Sector Educaci\xf3n', 'Sector Educaci\xf3n'), ('Sector Gubernamental', 'Sector Gubernamental'), ('Estudiante', 'Estudiante'), ('ONG', 'ONG'), ('No trabajo', 'No trabajo')], max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('puesto', models.CharField(choices=[('Presidente', 'Presidente'), ('CEO', 'CEO'), ('Founder', 'Founder'), ('Socio(a)', 'Socio(a)'), ('Rector', 'Rector'), ('Director(a)', 'Director(a)'), ('Subdirector(a)', 'Subdirector(a)'), ('Gerente', 'Gerente'), ('Subgerente', 'Subgerente'), ('Coordinador(a)', 'Coordinador(a)'), ('Supervisor(a)', 'Supervisor(a)'), ('Consultor(a)', 'Consultor(a)'), ('Contador(a)', 'Contador(a)'), ('Investigador(a)', 'Investigador(a)'), ('Asesor(a)', 'Asesor(a)'), ('Contralor(a)', 'Contralor(a)'), ('Lider de proyecto', 'Lider de proyecto'), ('Estudiante', 'Estudiante'), ('Perito', 'Perito'), ('Distribuidor(a)', 'Distribuidor(a)'), ('Gestor(a)', 'Gestor(a)'), ('Abogado(a)', 'Abogado(a)'), ('Conductor(a)', 'Conductor(a)'), ('Dise\xf1ador(a)', 'Dise\xf1ador(a)'), ('Secretario(a)', 'Secretario(a)'), ('Docente', 'Docente'), ('Diputado(a)', 'Diputado(a)'), ('Vendedor(a)', 'Vendedor(a)'), ('Delegado(a)', 'Delegado(a)'), ('Coach', 'Coach'), ('Capit\xe1n', 'Capit\xe1n'), ('Superintendente', 'Superintendente'), ('Ninguno', 'Ninguno'), ('Independiente', 'Independiente')], default=None, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Distrito Federal', 'Distrito Federal'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('M\xe9xico', 'M\xe9xico'), ('Michoac\xe1n', 'Michoac\xe1n'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Le\xf3n', 'Nuevo Le\xf3n'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Quer\xe9taro', 'Quer\xe9taro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potos\xed', 'San Luis Potos\xed'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucat\xe1n', 'Yucat\xe1n'), ('Zacatecas', 'Zacatecas')], max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('relacion_tec', models.CharField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Pap\xe1/Mam\xe1 Tec', 'Pap\xe1/Mam\xe1 Tec'), ('Ninguna', 'Ninguna')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default=None, max_length=300)),
                ('imagen_portada', models.ImageField(upload_to='portadas_eventos/%Y/%m/%D/')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('ponentes', models.CharField(max_length=300)),
                ('tipo_invitacion', multiselectfield.db.fields.MultiSelectField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Pap\xe1/Mam\xe1 Tec', 'Pap\xe1/Mam\xe1 Tec'), ('Ninguna', 'Ninguna')], max_length=120)),
                ('tipo_evento', models.CharField(choices=[('Desayuno empresarial', 'Desayuno empresarial'), ('Taller', 'Taller'), ('Sesi\xf3n de ideas que transforman', 'Sesi\xf3n de ideas que transforman'), ('Sesi\xf3n informativa Incubadora', 'Sesi\xf3n informativa Incubadora'), ('Sesi\xf3n informativa Enlace+', 'Sesi\xf3n informativa Enlace+'), ('', ''), ('Hackaton', 'Hackaton'), ('Conferencia', 'Conferencia'), ('Seminario', 'Seminario'), ('Enlace Day', 'Enlace Day'), ('BootCamp', 'BootCamp'), ('Convocatoria', 'Convocatoria'), ('Innovation & Bussines day', 'Innovation & Bussines day'), ('OTRO', 'OTRO')], max_length=200)),
                ('concepto_pago', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
