# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='tipo_evento',
            field=models.CharField(choices=[('Desayuno empresarial', 'Desayuno empresarial'), ('Taller', 'Taller'), ('Sesión de ideas que transforman', 'Sesión de ideas que transforman'), ('Sesión informativa Incubadora', 'Sesión informativa Incubadora'), ('Sesión informativa Enlace+', 'Sesión informativa Enlace+'), ('Hackaton', 'Hackaton'), ('Conferencia', 'Conferencia'), ('Seminario', 'Seminario'), ('Enlace Day', 'Enlace Day'), ('BootCamp', 'BootCamp'), ('Convocatoria', 'Convocatoria'), ('Innovation & Bussines day', 'Innovation & Bussines day'), ('OTRO', 'OTRO')], max_length=200),
        ),
    ]
