# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0002_auto_20190114_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono_celular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='puesto',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('CEO', 'CEO'), ('Founder', 'Founder'), ('Socio(a)', 'Socio(a)'), ('Rector', 'Rector'), ('Director(a)', 'Director(a)'), ('Subdirector(a)', 'Subdirector(a)'), ('Gerente', 'Gerente'), ('Subgerente', 'Subgerente'), ('Coordinador(a)', 'Coordinador(a)'), ('Supervisor(a)', 'Supervisor(a)'), ('Consultor(a)', 'Consultor(a)'), ('Contador(a)', 'Contador(a)'), ('Investigador(a)', 'Investigador(a)'), ('Asesor(a)', 'Asesor(a)'), ('Contralor(a)', 'Contralor(a)'), ('Lider de proyecto', 'Lider de proyecto'), ('Estudiante', 'Estudiante'), ('Perito', 'Perito'), ('Distribuidor(a)', 'Distribuidor(a)'), ('Gestor(a)', 'Gestor(a)'), ('Abogado(a)', 'Abogado(a)'), ('Conductor(a)', 'Conductor(a)'), ('Dise\xf1ador(a)', 'Dise\xf1ador(a)'), ('Secretario(a)', 'Secretario(a)'), ('Docente', 'Docente'), ('Diputado(a)', 'Diputado(a)'), ('Vendedor(a)', 'Vendedor(a)'), ('Delegado(a)', 'Delegado(a)'), ('Coach', 'Coach'), ('Capit\xe1n', 'Capit\xe1n'), ('Superintendente', 'Superintendente'), ('Ninguno', 'Ninguno'), ('Independiente', 'Independiente')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
