# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0003_auto_20190124_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono_celular',
            field=models.CharField(max_length=200),
        ),
    ]
