# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0004_auto_20190124_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='password',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
