# Generated by Django 2.1.7 on 2019-03-27 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartlink', '0008_auto_20190327_0453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Clientes',
        ),
    ]
