# Generated by Django 2.1.7 on 2019-03-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0009_auto_20190327_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='password',
        ),
    ]
