# Generated by Django 2.1.7 on 2019-03-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0010_remove_clientes_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='telefono',
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono_oficina',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono_celular',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
