# Generated by Django 2.1.7 on 2019-03-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0011_auto_20190327_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono_celular',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono_oficina',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
