# Generated by Django 2.1.7 on 2019-03-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0015_auto_20190327_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellidos',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ciudad',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='empresa',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Distrito Federal', 'Distrito Federal'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='ocupacion',
            field=models.CharField(choices=[('Sector Empresarial', 'Sector Empresarial'), ('Empresa propia', 'Empresa propia'), ('Sector Educación', 'Sector Educación'), ('Sector Gubernamental', 'Sector Gubernamental'), ('Estudiante', 'Estudiante'), ('ONG', 'ONG'), ('No trabajo', 'No trabajo')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='relacion_tec',
            field=models.CharField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Papá/Mamá Tec', 'Papá/Mamá Tec'), ('Ninguna', 'Ninguna')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono_celular',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono_oficina',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
