# Generated by Django 2.1.7 on 2019-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0016_auto_20190327_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='eventos',
            field=models.ManyToManyField(to='smartlink.Eventos'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='imagen_portada',
            field=models.ImageField(upload_to='portadas_eventos'),
        ),
    ]
