# Generated by Django 2.1.7 on 2019-05-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0017_auto_20190422_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='lugar',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
