# Generated by Django 2.1.7 on 2019-05-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0018_eventos_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_invitacion', models.CharField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Papá/Mamá Tec', 'Papá/Mamá Tec'), ('Ninguna', 'Ninguna')], default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='eventos',
            field=models.ManyToManyField(blank=True, to='smartlink.Eventos'),
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='tipo_invitacion',
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo_invitacion',
            field=models.ManyToManyField(to='smartlink.Choices'),
        ),
    ]
