# Generated by Django 2.1.7 on 2019-05-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0019_auto_20190508_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choices',
            options={'verbose_name_plural': 'Choices'},
        ),
    ]
