# Generated by Django 2.1.7 on 2019-05-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0021_auto_20190508_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='tipo',
            new_name='tipo_invitacion',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='name',
        ),
        migrations.AddField(
            model_name='choices',
            name='tipo_invitacion',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
