# Generated by Django 2.1.7 on 2019-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0022_auto_20190508_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='tipo_invitacion',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='choices',
            name='tipo_invitacion',
        ),
        migrations.AddField(
            model_name='choices',
            name='name',
            field=models.CharField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Papá/Mamá Tec', 'Papá/Mamá Tec'), ('Ninguna', 'Ninguna')], default=None, max_length=200, null=True),
        ),
    ]
