# Generated by Django 2.1.7 on 2019-05-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0023_auto_20190508_0632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Tipo_invitacion',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='tipo',
            new_name='tipo_invitacion',
        ),
    ]
