# Generated by Django 2.1.7 on 2019-05-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0024_auto_20190508_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_invitacion',
            options={'verbose_name_plural': 'Tipo de invitacion'},
        ),
        migrations.RenameField(
            model_name='tipo_invitacion',
            old_name='name',
            new_name='tipo',
        ),
    ]
