# Generated by Django 2.1.7 on 2019-05-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0026_auto_20190508_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='tipo_invitacion',
            field=models.CharField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Papá/Mamá Tec', 'Papá/Mamá Tec'), ('General', 'General')], default=None, max_length=200),
        ),
    ]
