# Generated by Django 2.1.7 on 2019-05-08 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartlink', '0029_remove_clientes_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='registros',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
