# Generated by Django 2.1.7 on 2019-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0030_eventos_registros'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
