# Generated by Django 2.1.7 on 2019-05-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0031_clientes_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'alta'), ('normal', 'normal')], default=None, max_length=200),
        ),
    ]
