# Generated by Django 2.1.7 on 2019-06-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0034_auto_20190620_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='relacion_tec',
            field=models.CharField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Papa/Mama Tec', 'Papa/Mama Tec'), ('Ninguna', 'Ninguna')], default=None, max_length=200, null=True),
        ),
    ]
