# Generated by Django 2.1.7 on 2019-06-20 03:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0035_auto_20190620_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='tipo_invitacion',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Papa/Mama Tec', 'Papa/Mama Tec'), ('General', 'General')], default=None, max_length=120),
        ),
    ]
