# Generated by Django 2.1.7 on 2019-06-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlink', '0042_auto_20190626_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='relacion_tec',
            field=models.CharField(choices=[('Alumno Profesional/Preparatoria', 'Alumno Profesional/Preparatoria'), ('Exatec', 'Exatec'), ('Alumno Maestria Tec', 'Alumno Maestria Tec'), ('Incubado Tec', 'Incubado Tec'), ('Consejero Tec', 'Consejero Tec'), ('Empleado Tec', 'Empleado Tec'), ('Padre/Madre Tec', 'Padre/Madre Tec'), ('Ninguna', 'Ninguna'), ('Exatec y Alumno Profesional/Preparatoria', 'Exatec y Alumno Profesional/Preparatoria'), ('Exatec y Alumno Maestria Tec', 'Exatec y Alumno Maestria Tec'), ('Exatec e Incubado Tec', 'Exatec e Incubado Tec'), ('Exatec y Consejero Tec', 'Exatec y Consejero Tec'), ('Exatec y Empleado Tec', 'Exatec y Empleado Tec'), ('Exatec y Padre/Madre Tec', 'Exatec y Padre/Madre Tec'), ('Incubado Tec y Consejero Tec', 'Incubado Tec y Consejero Tec'), ('Incubado Tec y Empleado Tec', 'Incubado Tec y Empleado Tec')], default=None, max_length=200, null=True),
        ),
    ]
